# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: sudhaacrrepo
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    tags: |
      sudhaacrrepo.azurecr.io/javaapp:latest
- task: Docker@2
  displayName: Push Docker Image to ACR
  inputs:
    command: push
    tags: |
      sudhaacrrepo.azurecr.io/javaapp:latest
